# Generated by Django 5.0.4 on 2024-04-14 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folderdata',
            name='file_docs',
            field=models.FileField(blank=True, null=True, upload_to='FolderData/docs'),
        ),
        migrations.AddField(
            model_name='folderdata',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FolderDataAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.folderdata')),
                ('users', models.ManyToManyField(blank=True, related_name='folderdataaccess_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.CharField(max_length=10)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
